### ISSUE TITLE
Do i have my directory right?

### ISSUE THREAD

**Issue by foong** [acarabott/supercollider-sublime#1]
i cant access the built system, did i get my directory right? Sorry, im new
![11](https://cloud.githubusercontent.com/assets/12502272/9897771/ea778718-5c7e-11e5-8733-1b7683528954.jpg)

![untitled](https://cloud.githubusercontent.com/assets/12502272/9897746/90f2a4d4-5c7e-11e5-88d4-69abe45f7345.jpg)

**Comment by acarabott** [comment]
Can you try without `scide.exe`, so it's just `C:\\Program Files (x86)\\SuperCollider-3.6.6\\`

**Comment by foong** [comment]
tried it with   "sc_dir": "C:\Program Files (x86)\SuperCollider-3.6.6\"  same results, is my file name correct? 
My package is in 
C:\Users\FOONG\AppData\Roaming\Sublime Text 3\Packages\SC\supercollider-sublime-master

**Comment by acarabott** [comment]
First, sorry you're having issues, I don't have a Windows machine to test on.
1. Can you try

```
"sc_dir": "C:\\Program Files (x86)\\SuperCollider-3.5.6",
"sc_exe": "sclang"
```
1. Can you take a screenshot of the SuperCollider-3.5.6 folder?
2. Open the SublimeText console (`ctrl ``) and look for anything related to this package in there, paste it in here.

**Comment by foong** [comment]
no worries, Im not sure that i got the console part right but here you go.
i also tried this, since the exe file name is scide.exe
"sc_dir": "C:\Program Files (x86)\SuperCollider-3.5.6",
"scide_exe": "sclang"   <---- this part here changed (im not sure what am i doing im just trying out) it still doesnt work.
![12](https://cloud.githubusercontent.com/assets/12502272/9934011/50ac7aa4-5d81-11e5-961e-9c7f0dcb61da.jpg)
![13](https://cloud.githubusercontent.com/assets/12502272/9934009/50a9c3d6-5d81-11e5-8015-a63c06f05e9a.jpg)
![14](https://cloud.githubusercontent.com/assets/12502272/9934007/50a7220c-5d81-11e5-980b-474d731ed756.jpg)
![15](https://cloud.githubusercontent.com/assets/12502272/9934008/50a71b22-5d81-11e5-92c8-fad212514cfb.jpg)

**Comment by acarabott** [comment]
Looks like the console will provide useful info, could you open it again,
and this time copy paste all (ctrl a) of the text there, instead of a
screenshot?

**Comment by foong** [comment]
DPI scale: 1.25
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/FOONG/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/FOONG/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/FOONG/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Package Control", "Vintage"]
pre session restore time: 0.0850248
startup time: 0.125025
first paint time: 0.125025
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Processing.Processing
plugins loaded
Running processing-java --force --sketch=C:\Users\FOONG\Downloads\M_1_5_03_TOOL --output=C:\Users\FOONG\Downloads\M_1_5_03_TOOL/build-tmp --run

> > > C:\Users\FOONG\AppData\Roaming\Sublime Text 3\Packages\SC\supercollider-sublime-master
> > >   File "<string>", line 1
> > >     C:\Users\FOONG\AppData\Roaming\Sublime Text 3\Packages\SC\supercollider-sublime-master
> > >      ^
> > > SyntaxError: invalid syntax

**Comment by acarabott** [comment]
Hey, I'm just setting up Windows on my machine, so hope to be able to
investigate this properly! Will let you know when it's resolved.

**Comment by foong** [comment]
thank you so much! looking forward to hear from you

**Comment by acarabott** [comment]
Hey, so first update to the latest version (I just made some minor changes).

Then rename the package folder to `supercollider-sublime` instead of `supercollider-sublime-master`.

You will need to restart Sublime Text after updating your config.
This config worked for me on Windows 7:

```
// SuperCollider directory (use double \\ in Windows)
"sc_dir": "C:\\Program Files (x86)\\SuperCollider-3.6.6",
// SCLang command name
"sc_exe": "sclang",
```

**Comment by acarabott** [comment]
Let me know if you get it working, I would _really_ appreciate your input on Windows keyboard shortcuts, as at the moment they are NOT good :)

**Comment by foong** [comment]
Hey there, Its still not working for me. Im not sure what did i do wrong.
So 
1. i downloaded the Zip
2. extracted it in C:\Users\FOONG\AppData\Roaming\Sublime Text 3\Packages\SC\supercollider- sublime-master
3. rename it to supercollider-sublime
4. update the config for the file SuperCollider sublime setting file.
5. start sublime

That's it right? Did i miss anything out?

**Comment by acarabott** [comment]
That sounds right.

Which version of Windows are you running? 

I can make a debug build that might help us solve this...

On Friday, 16 Oct 2015 at 14:52, foong notifications@github.com, wrote:

Hey there, Its still not working for me. Im not sure what did i do wrong.

So 
1. i downloaded the Zip
2. extracted it in C:\Users\FOONG\AppData\Roaming\Sublime Text 3\Packages\SC\supercollider- sublime-master
3. rename it to supercollider-sublime
4. update the config for the file SuperCollider sublime setting file.
5. start sublime

That's it right? Did i miss anything out?

**Comment by foong** [comment]
Sorry for the late reply, Im running windows 7 home premium, that would be great.

**Comment by acarabott** [comment]
Can you try installing from [package control](https://packagecontrol.io/installation), I've made it a lot easier to set the correct path.

If you still have the issue please re-open.
