### ISSUE TITLE
shortcuts not working

### ISSUE THREAD

**Issue by jd-m** [acarabott/supercollider-sublime#2]
Hi,
I've installed the package using the Github repository but the shortcuts do not work. Do you know any reason why that might be?

**Comment by acarabott** [comment]
Have you followed the installation instructions (in README) to set the correct path and exe for SuperCollider?

Which platform are you on?

**Comment by jd-m** [comment]
Sorry it was me being stupid and new to Sublime 3. It was that I wasn't using a .scd file but I have it working now and it is really great, Thanks!

**Comment by acarabott** [comment]
Glad you got it working :)
