### ISSUE TITLE
Trouble with Post window.

### ISSUE THREAD

**Issue by dotinspace** [acarabott/supercollider-sublime#3]
The Post window scrolls the text off-screen on every new event, so I have to manually scroll the text back into view to read it. Is this a known problem?

![sc-st3-error](https://cloud.githubusercontent.com/assets/1131221/12567325/b5ac2708-c3be-11e5-91ff-98f249a5cde2.png)

**Comment by acarabott** [comment]
Not a known issue, can you provide more details?
- OS
- Fullscreen?
- Sublime Text Theme
- Any other plugins that _could_ be involved?

**Comment by dotinspace** [comment]
Uhm... this is a bit embarrassing, the setting `scroll_past_end` in preferences was set to `true` for some reason. It's working now, set to `false`. So sorry about the fuss.
