### ISSUE TITLE
setup on osx 10.10.5

### ISSUE THREAD

**Issue by tatecarson** [acarabott/supercollider-sublime#4]
I'm trying to get this setup but i'm getting this greyed out menu. 
![screen shot 2016-05-08 at 1 38 13 pm](https://cloud.githubusercontent.com/assets/12865394/15100282/2a37d6c6-1522-11e6-9509-04c8106a4bac.png)

This is how I set the path: 
![screen shot 2016-05-08 at 1 36 47 pm](https://cloud.githubusercontent.com/assets/12865394/15100273/07ad0374-1522-11e6-854d-a15c0f0b49f4.png)

Am I doing something wrong here? I'm positive that's the correct path. 

thanks.

**Comment by acarabott** [comment]
It looks like there is an error in the settings file, although I can't spot it. 
Try this: 
- open the default settings file
- copy paste everything into your user settings file
- update your settings there

**Comment by tatecarson** [comment]
Do you mean the settings under Package settings -> SuperCollider? When I do that it says no such file or directory. At least it’s what I think you mean. Are you saying to make the user settings and default settings the same?

I also put the sc_dir into the global user settings and still the same. 

Sorry, i’m really new to Sublime Text, thanks for your help so far. 

-- 
Tate Carson
Sent with Airmail

On May 8, 2016 at 4:18:31 PM, Arthur Carabott (notifications@github.com) wrote:

It looks like there is an error in the settings file, although I can't spot it.
Try this:

open the default settings file
copy paste everything into your user settings file
update your settings there

**Comment by acarabott** [comment]
Can you make sure that your folder is called `supercollider-sublime` so that the structure is `Packages/supercollider-sublime`

Then from the top OS menu: `Sublime Text  > Preferences > Package Settings > SuperCollider > Settings - Default`

I'd be surprised if there is no file, but you can put this as your user settings, then you can adjust any of them as you like

```
{
    // SuperCollider directory (use double \\ in Windows)
    "sc_dir": "/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/",
    // SCLang command name
    "sc_exe": "sclang",
    // Maximum number of lines in for Post window
    // If you are printing a *lot* very quickly then reducing this will reduce
    // CPU load.
    // -1 for no limit, ok for general use but not for extreme printing
    "max_post_view_lines": 1000,
    // Whether to syntax highlight the post view, use either "True" or "False"
    "highlight_post_view": "True",
    // Where to open the post view
    // options: group|tab|window|panel
    "open_post_view_in": "group",
    "word_separators": "./\\()\"'-:,.;<>!@#$%^&*|+=[]{}`?",
    // this flag is prefixed to messages that should be handled differently by
    // SublimeText, i.e. not just appended to the post window
    // If you are using this string in your code (for some reason) and are
    // getting conflicts, change it to something else
    "stdout_flag": "***___SUBLIME___***"
}
```

**Comment by tatecarson** [comment]
Ok firstly I think I was having problems because the folder was named supercollider-sublime-master from github. Changed that and now the menu is un-greyed but when I go to start interpreter I get this in the console: 
error: Could not start sclang
Please check your SuperCollider.sublime-settings file
Then restart Sublime Text
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 538, in run_
    return self.run()
  File "/Users/tatecarson/Library/Application Support/Sublime Text 3/Packages/supercollider-sublime/SuperCollider.py", line 400, in run
    sc.start()
  File "/Users/tatecarson/Library/Application Support/Sublime Text 3/Packages/supercollider-sublime/SuperCollider.py", line 171, in start
    self.sclang_process.stdout,
AttributeError: 'NoneType' object has no attribute 'stdout'

Here’s my file structure, is this correct? 

-- 
Tate Carson
Sent with Airmail

On May 9, 2016 at 1:29:20 AM, Arthur Carabott (notifications@github.com) wrote:

Can you make sure that your folder is called supercollider-sublime so that the structure is Packages/supercollider-sublime

Then from the top OS menu: Sublime Text > Preferences > Package Settings > SuperCollider > Settings - Default

I'd be surprised if there is no file, but you can put this as your user settings, then you can adjust any of them as you like

{
    // SuperCollider directory (use double \ in Windows)
    "sc_dir": "/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/",
    // SCLang command name
    "sc_exe": "sclang",
    // Maximum number of lines in for Post window
    // If you are printing a _lot_ very quickly then reducing this will reduce
    // CPU load.
    // -1 for no limit, ok for general use but not for extreme printing
    "max_post_view_lines": 1000,
    // Whether to syntax highlight the post view, use either "True" or "False"
    "highlight_post_view": "True",
    // Where to open the post view
    // options: group|tab|window|panel
    "open_post_view_in": "group",
    "word_separators": "./\()\"'-:,.;<>!@#$%^&_|+=[]{}`?",
    // this flag is prefixed to messages that should be handled differently by
    // SublimeText, i.e. not just appended to the post window
    // If you are using this string in your code (for some reason) and are
    // getting conflicts, change it to something else
    "stdout_flag": "_****_SUBLIME**_***"
}

**Comment by acarabott** [comment]
Your file structure looks correct. Unfortunately it it unable to start sclang, this is probably because it can't find the sclang executable.

Can you find the `SuperCollider.app` in the Finder, right click it and select `Show Package Contents`

I want to check that the internals of your `SuperCollider.app` are structured like this. If not let me know which version of SuperCollider you are using.

![sc-structure](https://cloud.githubusercontent.com/assets/66132/15287051/5c6fd2cc-1b9b-11e6-81c0-88fec35dfab1.png)

**Comment by acarabott** [comment]
Closing this as no response, let me know if still unsolved.

**Comment by precabal** [comment]
Hi there, was having a similar issue on OS X 10.9.5, installed through Package Control and the settings under Sublime Text > Preferences > Package Settings > SuperCollider > Settings - Default were showing up empty. I got the following error when trying to boot the interpreter:

Error loading syntax file "Packages/supercollider-sublime/SuperCollider.tmLanguage": Unable to open Packages/supercollider-sublime/SuperCollider.tmLanguage

When pasting the lines you suggested above for my user settings, the error went away.
