### ISSUE TITLE
How to disable all shortcuts?

### ISSUE THREAD

**Issue by nhthn** [acarabott/supercollider-sublime#5]
I just want to use this for syntax highlighting and don't need any of the default key bindings. Any way I can disable them? ctrl+s does not work for saving anymore.

**Comment by acarabott** [comment]
You can override all shortcuts by creating a "User (Windows).sublime-keymap" file and overriding the defaults.

Lazily I had just copied the Mac shortcuts to Windows and Linux without thinking about it!

Would you be interested in contributing a set of Windows shortcuts? I, and others would really appreciate it!

**Comment by nhthn** [comment]
I don't want to change them to other shortcuts -- I just want to remove them completely since I don't need that functionality. All four of the settings files under Package Settings > SuperCollider are blank so I'm not sure what I specifically need to add to get rid of them.

**Comment by acarabott** [comment]
You need to override them. Copy all of the settings from the "Default..." file to your User file and set the short cut to an empty string ""

**Comment by nhthn** [comment]
Both "Settings - Default" and "Key Bindings - Default" are blank, so I copied from GitHub. When I tried to save "Key Bindings - User", I received a "file not found" error because I was attempting to save in a nonexistent directory `~/.config/sublime-text-3/Packages/supercollider-sublime/`. Even after creating that directory, saving, and restarting Sublime, I see no change in behavior.

**Comment by acarabott** [comment]
I'm getting on a plane, so I suggest having a look at http://docs.sublimetext.info/en/latest/customization/key_bindings.html until I am back online in a week. Thanks for your patience

**Comment by nhthn** [comment]
No worries. Have a safe trip!

**Comment by acarabott** [comment]
I've just updated the package via package control, with all key bindings disabled for windows/linux.

it may take an hour or so to become available. You should get a message when you re-open sublime text and the package updates.

You can also unbind any key command like so (in your global key bindings file):

`[ { "keys": ["ctrl+t"], "command": "unbound" } ]`

The full list of key commands I had used is:
- `["ctrl+s", "ctrl+s"]`
- `["ctrl+s", "ctrl+t", "ctrl+t"]`
- `["shift+enter"]`
- `["super+enter"]`
- `["super+shift+enter"]`
- `["ctrl+s", "ctrl+o"]`
- `["super+shift+c"]`
- `["super+b"]`
- `["ctrl+s", "ctrl+k", "ctrl+k"]`
- `["ctrl+s", "ctrl+b", "ctrl+b"]`
- `["super+ctrl+m"]`
- `["super+ctrl+="]`
- `["super+ctrl+-"]`
- `["super+ctrl+0"]`
- `["ctrl+s", "ctrl+r"]`
- `["ctrl+s", "ctrl+p"]`
- `["super+enter"]`
- `["super+."]`
- `["ctrl+s", "ctrl+l", "ctrl+l"]`
- `["ctrl+s", "ctrl+d"]`
- `["ctrl+s", "ctrl+c"]`

**Comment by nhthn** [comment]
Thanks heaps!

**Comment by acarabott** [comment]
If you do end up binding keys, let me know what they are!
Some (like "super+." to stop all sounds) are indispensable !
