### ISSUE TITLE
User Key Binding Not working

### ISSUE THREAD

**Issue by jd-m** [acarabott/supercollider-sublime#6]
Hi, 
Firstly, thanks for the great package,
secondly when I try to set my own key mapping it does not seem to work. 
Might you know why?
I put this in the User SuperCollider.sublime-keymap 

```
{
        "command": "super_collider_open_post_view",
        "keys":    ["ctrl+w","ctrl+w"],
        "context": [{
            "key":      "selector",
            "operator": "equal",
            "operand":  "source.supercollider"
        }]
    }
```

Thanks

**Comment by acarabott** [comment]
In case this is still an issue, a new version has been released. Once it's updated in package control this should be much simpler, just select `Key Bindings` from `Preferences/Package Settings/Supercollider` and copy from the original.
