### ISSUE TITLE
.loadRelative doesn't work

### ISSUE THREAD

**Issue by tesla9** [acarabott/supercollider-sublime#9]
loadRelative function always causes an error:
"ERROR: can't load relative to an unsaved"

**Comment by acarabott** [comment]
This is because `loadRelative` calls `thisProcess.nowExecutingPath` which according to the docs...

> This method is supported in the SuperCollider IDE, the Macintosh-only SuperCollider.app, and the scel (SuperCollider-Emacs-Lisp) environment. In other editor environments, it will return nil.

So unfortunately this is not possible from within Sublime.

**Comment by tesla9** [comment]
super!, thank you for quick response and explanation.
